default["ha"]["available_services"]["keystone-admin-api"] = {
    "role" => "keystone-api",
    "namespace" => "keystone",
    "service" => "admin-api",
    "service_type" => "identity",
    "lb_mode" => "http",
    "lb_algorithm" => "roundrobin",
    "lb_options" => ["forwardfor", "httpchk", "httplog"],
    "vrid" => 12,
    "vip_network" => "public"
}
default["ha"]["available_services"]["keystone-service-api"] = {
    "role" => "keystone-api",
    "namespace" => "keystone",
    "service" => "service-api",
    "service_type" => "identity",
    "lb_mode" => "http",
    "lb_algorithm" => "roundrobin",
    "lb_options" => ["forwardfor", "httpchk", "httplog"],
    "vrid" => 13,
    "vip_network" => "public"
}
default["ha"]["available_services"]["nova-api"] = {
    "role" => "nova-api-os-compute",
    "namespace" => "nova",
    "service" => "api",
    "service_type" => "compute",
    "lb_mode" => "http",
    "lb_algorithm" => "roundrobin",
    "lb_options" => ["forwardfor", "httpchk", "httplog"],
    "vrid" => 14,
    "vip_network" => "public"
}
default["ha"]["available_services"]["nova-admin-api"] = {
    "role" => "nova-api-os-compute",
    "namespace" => "nova",
    "service" => "admin-api",
    "service_type" => "compute",
    "lb_mode" => "http",
    "lb_algorithm" => "roundrobin",
    "lb_options" => ["forwardfor", "httpchk", "httplog"],
    "vrid" => 15,
    "vip_network" => "management"
}
default["ha"]["available_services"]["nova-internal-api"] = {
    "role" => "nova-api-os-compute",
    "namespace" => "nova",
    "service" => "internal-api",
    "service_type" => "compute",
    "lb_mode" => "http",
    "lb_algorithm" => "roundrobin",
    "lb_options" => ["forwardfor", "httpchk", "httplog"],
    "vrid" => 16,
    "vip_network" => "management"
}
default["ha"]["available_services"]["nova-ec2-public"] = {
    "role" => "nova-api-ec2",
    "namespace" => "nova",
    "service" => "ec2-public",
    "service_type" => "ec2",
    "lb_mode" => "http",
    "lb_algorithm" => "roundrobin",
    "lb_options" => [],
    "vrid" => 17,
    "vip_network" => "public"
}
default["ha"]["available_services"]["cinder-api"] = {
    "role" => "cinder-api",
    "namespace" => "cinder",
    "service" => "api",
    "service_type" => "volume",
    "lb_mode" => "http",
    "lb_algorithm" => "roundrobin",
    "lb_options" => ["forwardfor", "httpchk", "httplog"],
    "vrid" => 18,
    "vip_network" => "public"
}
default["ha"]["available_services"]["cinder-admin-api"] = {
    "role" => "cinder-api",
    "namespace" => "cinder",
    "service" => "admin-api",
    "service_type" => "volume",
    "lb_mode" => "http",
    "lb_algorithm" => "roundrobin",
    "lb_options" => ["forwardfor", "httpchk", "httplog"],
    "vrid" => 19,
    "vip_network" => "management"
}
default["ha"]["available_services"]["cinder-internal-api"] = {
    "role" => "cinder-api",
    "namespace" => "cinder",
    "service" => "internal-api",
    "service_type" => "volume",
    "lb_mode" => "http",
    "lb_algorithm" => "roundrobin",
    "lb_options" => ["forwardfor", "httpchk", "httplog"],
    "vrid" => 20,
    "vip_network" => "management"
}
default["ha"]["available_services"]["glance-api"] = {
    "role" => "glance-api",
    "namespace" => "glance",
    "service" => "api",
    "service_type" => "image",
    "lb_mode" => "http",
    "lb_algorithm" => "roundrobin",
    "lb_options" => ["forwardfor", "httpchk", "httplog"],
    "vrid" => 21,
    "vip_network" => "public"
}
default["ha"]["available_services"]["glance-admin-api"] = {
    "role" => "glance-api",
    "namespace" => "glance",
    "service" => "admin-api",
    "service_type" => "image",
    "lb_mode" => "http",
    "lb_algorithm" => "roundrobin",
    "lb_options" => ["forwardfor", "httpchk", "httplog"],
    "vrid" => 22,
    "vip_network" => "management"
}
default["ha"]["available_services"]["glance-internal-api"] = {
    "role" => "glance-api",
    "namespace" => "glance",
    "service" => "internal-api",
    "service_type" => "image",
    "lb_mode" => "http",
    "lb_algorithm" => "roundrobin",
    "lb_options" => ["forwardfor", "httpchk", "httplog"],
    "vrid" => 23,
    "vip_network" => "management"
}
default["ha"]["available_services"]["swift-proxy"] = {
    "role" => "swift-proxy-server",
    "namespace" => "swift",
    "service" => "proxy",
    "service_type" => "object-store",
    "lb_mode" => "http",
    "lb_algorithm" => "roundrobin",
    "lb_options" => [],
    "vrid" => 24,
    "vip_network" => "public"
}
default["ha"]["available_services"]["glance-registry"] = {
    "role" => "glance-registry",
    "namespace" => "glance",
    "service" => "registry",
    "service_type" => "image",
    "lb_mode" => "http",
    "lb_algorithm" => "roundrobin",
    "lb_options" => [],
    "vrid" => 25,
    "vip_network" => "public"
}
default["ha"]["available_services"]["nova-novnc-proxy"] = {
    "role" => "nova-vncproxy",
    "namespace" => "nova",
    "service" => "novnc-proxy",
    "service_type" => "compute",
    "lb_mode" => "tcp",
    "lb_algorithm" => "source",
    "lb_options" => [],
    "vrid" => 26,
    "vip_network" => "public"
}
default["ha"]["available_services"]["nova-xvpvnc-proxy"] = {
    "role" => "nova-vncproxy",
    "namespace" => "nova",
    "service" => "xvpvnc-proxy",
    "service_type" => "compute",
    "lb_mode" => "tcp",
    "lb_algorithm" => "source",
    "lb_options" => [],
    "vrid" => 27,
    "vip_network" => "public"
}
default["ha"]["available_services"]["horizon-dash"] = {
    "role" => "horizon-server",
    "namespace" => "horizon",
    "service" => "dash",
    "service_type" => "dash",
    "lb_mode" => "http",
    "lb_algorithm" => "roundrobin",
    "lb_options" => ["forwardfor", "httpchk", "httplog"],
    "vrid" => 28,
    "vip_network" => "public"
}
default["ha"]["available_services"]["horizon-dash_ssl"] = {
    "role" => "horizon-server",
    "namespace" => "horizon",
    "service" => "dash_ssl",
    "service_type" => "dash",
    "lb_mode" => "tcp",
    "lb_algorithm" => "source",
    "lb_options" => [],
    "vrid" => 29,
    "vip_network" => "public"
}
default["ha"]["available_services"]["ceilometer-api"] = {
    "role" => "ceilometer-api",
    "namespace" => "ceilometer",
    "service" => "api",
    "service_type" => "metering",
    "lb_mode" => "http",
    "lb_algorithm" => "roundrobin",
    "lb_options" => [],
    "vrid" => 30,
    "vip_network" => "public"
}
default["ha"]["available_services"]["ceilometer-admin-api"] = {
    "role" => "ceilometer-api",
    "namespace" => "ceilometer",
    "service" => "admin-api",
    "service_type" => "metering",
    "lb_mode" => "http",
    "lb_algorithm" => "roundrobin",
    "lb_options" => [],
    "vrid" => 31,
    "vip_network" => "management"
}
default["ha"]["available_services"]["ceilometer-internal-api"] = {
    "role" => "ceilometer-api",
    "namespace" => "ceilometer",
    "service" => "internal-api",
    "service_type" => "metering",
    "lb_mode" => "http",
    "lb_algorithm" => "roundrobin",
    "lb_options" => [],
    "vrid" => 32,
    "vip_network" => "management"
}

default['ha']['swift-only'] = false
